# Generated by Django 2.2 on 2019-04-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurfReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('local_time', models.DateTimeField()),
                ('min_swell', models.IntegerField()),
                ('max_swell', models.IntegerField()),
            ],
        ),
    ]
