# Generated by Django 2.2 on 2019-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfreport',
            name='max_swell',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='surfreport',
            name='min_swell',
            field=models.FloatField(),
        ),
    ]
