# Generated by Django 2.2 on 2019-04-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf', '0003_auto_20190410_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='surfreport',
            name='tags',
            field=models.ManyToManyField(to='surf.Tag'),
        ),
    ]
