# Generated by Django 2.2 on 2019-04-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf', '0004_auto_20190411_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
