# Generated by Django 2.2 on 2019-04-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf', '0005_auto_20190413_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfreport',
            name='note',
            field=models.TextField(default='', max_length=150),
        ),
    ]
