# Generated by Django 2.2 on 2019-04-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf', '0006_surfreport_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfreport',
            name='note',
            field=models.TextField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='surfreport',
            index=models.Index(fields=['note'], name='surf_surfre_note_dca679_idx'),
        ),
    ]
